### PR TITLE
Build on current sensu-go GA RC sha

### PR DESCRIPTION
**Pull request by portertech**
Signed-off-by: Sean Porter <portertech@gmail.com>

Closes https://github.com/sensu/sensu-slack-handler/issues/6

### CODE REVIEW

**Comment by nikkictl** [comment]
giphy

**Comment by portertech** [comment]
catwalk

**Comment by portertech** [comment]
My master branch has diverged 🔥 going to clean this up one more time ☠️

**Review by nikkictl — APPROVED** [review]
💯

**Pull request merged**
